/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moyano_elliot.ApartadoB;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Luces extends javax.swing.JFrame {

    /**
     * Creates new form Luces
     */
    String URL_assets = "src/moyano_elliot/ApartadoB/assets/";
    String encendido = URL_assets + "1.png";
    String apagado = URL_assets + "0.png";
    ArrayList<JButton> bombillas;
    int numBotones;

    int intentos;
    boolean encendidas;

    public Luces() {
        initComponents();
        setLocationRelativeTo(null);
        elegirBotones();
        eventoBotones();
        asignarID();
        insertarImagenes();
        intentos = 0;
        encendidas = false;

    }

    private void elegirBotones() {
        do {
            String cantidadBotones = JOptionPane.showInputDialog("Elige la cantidad de botones (3 a 20)");
            try {
                numBotones = Integer.parseInt(cantidadBotones);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe ser un numero entero");
            }
        } while (numBotones < 3 || numBotones > 20);
    }

    private void eventoBotones() {
        bombillas = new ArrayList<>();
        for (int i = 0; i < numBotones; i++) {
            JButton boton = new JButton();
            bombillas.add(boton);
            jPanel1.add(boton);
        }
        for (JButton button : bombillas) {
            button.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pulsarBombilla(evt);
                }
            });
        }
    }

    private void asignarID() {
        for (int i = 0; i < bombillas.size(); i++) {
            bombillas.get(i).setName(String.valueOf(i));
        }
    }

    private void insertarImagenes() {
        for (JButton button : bombillas) {
            button.setIcon(new ImageIcon(URL_assets + "0.png"));
        }
    }

    private void reproducirSonido() {
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File("src/moyano_elliot/ApartadoB/assets/sonido.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println("Error al reproducir sonido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reiniciar = new javax.swing.JButton();
        intentoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 300));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 163));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        reiniciar.setText("Volver a empezar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        intentoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        intentoLabel.setText("Intentos: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(intentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1030, Short.MAX_VALUE)
                .addComponent(reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reiniciar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        insertarImagenes();
    }//GEN-LAST:event_reiniciarActionPerformed

    private void pulsarBombilla(java.awt.event.ActionEvent evt) {
        JButton boton = (JButton) evt.getSource(); // pillo el boton que ha saltado el evento
        cambiarEstado(boton);
        reproducirSonido();
    }

    private void cambiarEstado(JButton boton) {
        int botonName = Integer.parseInt(boton.getName()); // paso la "id" a int
        if (boton.getName().equals("0")) { // si es el primero, que solo cambie el de la derecha
            bombillas.get(botonName + 1).setIcon((bombillas.get(botonName + 1).getIcon().toString().equals(encendido)) ? new ImageIcon(apagado) : new ImageIcon(encendido));
        } else if (boton.getName().equals(String.valueOf(bombillas.size() - 1))) { // si es el ultimo que cambie el de la izquierda
            bombillas.get(botonName - 1).setIcon((bombillas.get(botonName - 1).getIcon().toString().equals(encendido)) ? new ImageIcon(apagado) : new ImageIcon(encendido));
        } else { // si no es ultimo ni primero
            bombillas.get(botonName - 1).setIcon((bombillas.get(botonName - 1).getIcon().toString().equals(encendido)) ? new ImageIcon(apagado) : new ImageIcon(encendido));
            bombillas.get(botonName + 1).setIcon((bombillas.get(botonName + 1).getIcon().toString().equals(encendido)) ? new ImageIcon(apagado) : new ImageIcon(encendido));
            // en estas condiciones compruebo que si esta encendido se apaga y viceversa
        }
        intentos++;
        intentoLabel.setText("Intentos: " + String.valueOf(intentos));
        comprobarEstados();
    }

    private void comprobarEstados() {
        int contador = 0;
        for (JButton boton : bombillas) {
            if (boton.getIcon().toString().equals(encendido)) {
                contador++;
            }
        }
        if (contador == bombillas.size()) {
            JOptionPane.showMessageDialog(this, "Has ganado!");
            insertarImagenes();
            intentos = 0;
            intentoLabel.setText("Intentos: " + String.valueOf(intentos));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Luces.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Luces.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Luces.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Luces.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Luces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel intentoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reiniciar;
    // End of variables declaration//GEN-END:variables
}
