/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.E147;

/**
 *
 * @author Elliot
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;

import java.util.HashMap;
import java.util.ArrayList;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private HashMap<String, Usuario> datos;
    private Menu menu;
    private String nombre;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        ventanaCrearCuenta.setLocationRelativeTo(null);
        datos = new HashMap<>();
        leerDatos();
        error.setVisible(false);
        errorCrear.setVisible(false);

    }

    private void leerDatos() {
        String RUTA_DATOS = "src/Interfaces/E147/ficheros/datos.txt";
        try ( BufferedReader br = new BufferedReader(new FileReader(RUTA_DATOS))) {
            String linea;
            do {
                linea = br.readLine();
                if (linea != null) {
                    nombre = linea.split(":")[0];
                    String password = linea.split(":")[1];
                    ArrayList<Integer> stats = new ArrayList<>();
                    stats.add(Integer.parseInt(linea.split(":")[2]));
                    stats.add(Integer.parseInt(linea.split(":")[3]));
                    stats.add(Integer.parseInt(linea.split(":")[4]));
                    this.datos.put(nombre, new Usuario(password, stats));
                }
            } while (linea != null);
        } catch (java.io.FileNotFoundException e) {
            System.out.println("No se encontró el fichero");
        } catch (java.io.IOException e) {
            System.out.println("Error al leer fichero");
        }
    }

    private void escribirDatos() {
        String RUTA_DATOS = "src/Interfaces/E147/ficheros/datos.txt";
        try ( BufferedWriter bw = new BufferedWriter(new FileWriter(RUTA_DATOS))) {
            for (String user : this.datos.keySet()) {
                bw.append(user + ":" + this.datos.get(user).getPassword() + ":" + this.datos.get(user).getStats().toString().replaceAll("[\\[\\]]", "").replace(", ", ":") + System.lineSeparator());
            }
        } catch (java.io.IOException e) {
            System.out.println("Error al escribir fichero");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaCrearCuenta = new javax.swing.JFrame();
        crearNombre = new javax.swing.JTextField();
        crearPassword = new javax.swing.JPasswordField();
        crearCuentaConfirmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confirmarPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        errorCrear = new javax.swing.JLabel();
        cuentaYaRegistrada = new javax.swing.JButton();
        textoUsuario = new javax.swing.JTextField();
        textoPassword = new javax.swing.JPasswordField();
        iniciarSesion = new javax.swing.JButton();
        crearCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        ventanaCrearCuenta.setResizable(false);
        ventanaCrearCuenta.setSize(new java.awt.Dimension(410, 300));
        ventanaCrearCuenta.setType(java.awt.Window.Type.POPUP);
        ventanaCrearCuenta.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ventanaCrearCuenta.getContentPane().add(crearNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 388, -1));
        ventanaCrearCuenta.getContentPane().add(crearPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, 388, -1));

        crearCuentaConfirmar.setText("Crear cuenta");
        crearCuentaConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaConfirmarActionPerformed(evt);
            }
        });
        ventanaCrearCuenta.getContentPane().add(crearCuentaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Crear Cuenta");
        ventanaCrearCuenta.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 388, 27));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Contraseña");
        ventanaCrearCuenta.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 388, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nombre de usuario");
        ventanaCrearCuenta.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, 388, -1));
        ventanaCrearCuenta.getContentPane().add(confirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 176, 388, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Confirmar Contraseña");
        ventanaCrearCuenta.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 388, -1));

        errorCrear.setForeground(new java.awt.Color(255, 51, 51));
        errorCrear.setText("Error");
        ventanaCrearCuenta.getContentPane().add(errorCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 204, 388, -1));

        cuentaYaRegistrada.setText("¿Ya tienes una cuenta?");
        cuentaYaRegistrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaYaRegistradaActionPerformed(evt);
            }
        });
        ventanaCrearCuenta.getContentPane().add(cuentaYaRegistrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 232, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, 388, -1));
        getContentPane().add(textoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 143, 388, -1));

        iniciarSesion.setText("Iniciar sesion");
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, -1, -1));

        crearCuenta.setText("Crear cuenta");
        crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(crearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 203, 101, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Iniciar sesion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 388, 27));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, 388, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre de usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, 388, -1));

        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setText("Usuario o contraseña incorrectos.");
        getContentPane().add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 388, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed

        if (this.datos.containsKey(textoUsuario.getText()) && this.datos.get(textoUsuario.getText()).getPassword().equals(String.valueOf(textoPassword.getPassword()))) {
            if (menu == null) {
                nombre = textoUsuario.getText();
                menu = new Menu();
                menu.cambiarStats(this.datos.get(nombre).getStats().get(0), this.datos.get(nombre).getStats().get(1), this.datos.get(nombre).getStats().get(2));
                menu.cambiarTexto(nombre);
                menu.setVisible(true);
                this.dispose();
            }
        } else {
            error.setVisible(true);
            textoUsuario.setText("");
            textoPassword.setText("");
        }
    }//GEN-LAST:event_iniciarSesionActionPerformed

    private ArrayList<Integer> crearStats() {
        ArrayList<Integer> newStats = new ArrayList<>();
        newStats.add(0);
        newStats.add(0);
        newStats.add(0);
        return newStats;
    }

    private void crearCuentaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaConfirmarActionPerformed
        if (!this.datos.containsKey(crearCuenta.getText())) {
            if (!crearNombre.getText().isBlank() && !String.valueOf(crearPassword.getPassword()).isBlank() && !crearNombre.getText().contains(" ") && String.valueOf(crearPassword.getPassword()).equals(String.valueOf(confirmarPassword.getPassword()))) {
                this.datos.put(crearNombre.getText(), new Usuario(String.valueOf(confirmarPassword.getPassword()), crearStats()));
                escribirDatos();
                ventanaCrearCuenta.setVisible(false);
                this.setVisible(true);
            } else {
                errorCrear.setVisible(true);
                errorCrear.setText("Datos incorrectos");
            }
        } else {
            errorCrear.setVisible(true);
            errorCrear.setText("Ya existe una cuenta");
        }
    }//GEN-LAST:event_crearCuentaConfirmarActionPerformed

    private void cuentaYaRegistradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaYaRegistradaActionPerformed
        this.setVisible(true);
        ventanaCrearCuenta.setVisible(false);
    }//GEN-LAST:event_cuentaYaRegistradaActionPerformed

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaActionPerformed
        ventanaCrearCuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmarPassword;
    private javax.swing.JButton crearCuenta;
    private javax.swing.JButton crearCuentaConfirmar;
    private javax.swing.JTextField crearNombre;
    private javax.swing.JPasswordField crearPassword;
    private javax.swing.JButton cuentaYaRegistrada;
    private javax.swing.JLabel error;
    private javax.swing.JLabel errorCrear;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField textoPassword;
    private javax.swing.JTextField textoUsuario;
    private javax.swing.JFrame ventanaCrearCuenta;
    // End of variables declaration//GEN-END:variables
}
