/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.E147;

/**
 *
 * @author Elliot
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Cartas JuegoMemoria;
    private ParesNones JuegoParesNones;

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventanaElegirJuego.setLocationRelativeTo(null);
        this.ventanaEstadisticas.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaEstadisticas = new javax.swing.JFrame();
        labelPartidasCartas = new javax.swing.JLabel();
        labelVictoriasPN = new javax.swing.JLabel();
        labelDerrotasPN = new javax.swing.JLabel();
        volverES = new javax.swing.JButton();
        ventanaElegirJuego = new javax.swing.JFrame();
        volverEJ = new javax.swing.JButton();
        paresNones = new javax.swing.JButton();
        cartas = new javax.swing.JButton();
        estadisticas = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        elegirJuego = new javax.swing.JButton();
        mensajeBienvenida = new javax.swing.JLabel();

        ventanaEstadisticas.setUndecorated(true);
        ventanaEstadisticas.setResizable(false);
        ventanaEstadisticas.setSize(new java.awt.Dimension(400, 300));

        labelPartidasCartas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPartidasCartas.setText("Partidas jugadas a las cartas:");

        labelVictoriasPN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelVictoriasPN.setText("Victorias pares y nones: ");

        labelDerrotasPN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDerrotasPN.setText("Derrotas pares y nones: ");

        volverES.setText("Volver");
        volverES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaEstadisticasLayout = new javax.swing.GroupLayout(ventanaEstadisticas.getContentPane());
        ventanaEstadisticas.getContentPane().setLayout(ventanaEstadisticasLayout);
        ventanaEstadisticasLayout.setHorizontalGroup(
            ventanaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelDerrotasPN, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(labelPartidasCartas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelVictoriasPN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEstadisticasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverES, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ventanaEstadisticasLayout.setVerticalGroup(
            ventanaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEstadisticasLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(labelVictoriasPN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDerrotasPN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPartidasCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(volverES, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ventanaElegirJuego.setUndecorated(true);
        ventanaElegirJuego.setResizable(false);
        ventanaElegirJuego.setSize(new java.awt.Dimension(400, 300));

        volverEJ.setText("Volver");
        volverEJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverEJActionPerformed(evt);
            }
        });

        paresNones.setText("Pares y Nones");
        paresNones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paresNonesActionPerformed(evt);
            }
        });

        cartas.setText("Memorizar Cartas");
        cartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaElegirJuegoLayout = new javax.swing.GroupLayout(ventanaElegirJuego.getContentPane());
        ventanaElegirJuego.getContentPane().setLayout(ventanaElegirJuegoLayout);
        ventanaElegirJuegoLayout.setHorizontalGroup(
            ventanaElegirJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaElegirJuegoLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(ventanaElegirJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cartas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paresNones, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverEJ, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );
        ventanaElegirJuegoLayout.setVerticalGroup(
            ventanaElegirJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaElegirJuegoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(paresNones, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volverEJ, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 300));

        estadisticas.setText("Estadisticas");
        estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        elegirJuego.setText("Elegir juego");
        elegirJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirJuegoActionPerformed(evt);
            }
        });

        mensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensajeBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeBienvenida.setText("Bienvenido, usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elegirJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(estadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(mensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(elegirJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void volverESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverESActionPerformed
        this.ventanaEstadisticas.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_volverESActionPerformed

    private void volverEJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverEJActionPerformed
        this.ventanaElegirJuego.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_volverEJActionPerformed

    private void cartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartasActionPerformed
        if (this.JuegoMemoria == null) {
            this.JuegoMemoria = new Cartas();
            this.JuegoMemoria.setVisible(true);
            this.ventanaElegirJuego.dispose();
        }
    }//GEN-LAST:event_cartasActionPerformed

    private void paresNonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paresNonesActionPerformed
        if (this.JuegoParesNones == null) {
            this.JuegoParesNones = new ParesNones();
            this.JuegoParesNones.setVisible(true);
            this.ventanaElegirJuego.dispose();
        }
    }//GEN-LAST:event_paresNonesActionPerformed

    private void elegirJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirJuegoActionPerformed
        this.ventanaElegirJuego.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_elegirJuegoActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasActionPerformed
        this.ventanaEstadisticas.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_estadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartas;
    private javax.swing.JButton elegirJuego;
    private javax.swing.JButton estadisticas;
    private javax.swing.JLabel labelDerrotasPN;
    private javax.swing.JLabel labelPartidasCartas;
    private javax.swing.JLabel labelVictoriasPN;
    private javax.swing.JLabel mensajeBienvenida;
    private javax.swing.JButton paresNones;
    private javax.swing.JButton salir;
    private javax.swing.JFrame ventanaElegirJuego;
    private javax.swing.JFrame ventanaEstadisticas;
    private javax.swing.JButton volverEJ;
    private javax.swing.JButton volverES;
    // End of variables declaration//GEN-END:variables
}
