/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.EquiposAleatorios;

/**
 *
 * @author Elliot
 */
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class Equipos extends javax.swing.JFrame {

    /**
     * Creates new form Equipos
     */
    ArrayList<String> listaJugadores;

    public Equipos() {
        initComponents();

        setLocationRelativeTo(null);
        tablaFrame.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaFrame = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        salir = new javax.swing.JButton();
        rehacer = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        nJugadores = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        tablaFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        tablaFrame.setPreferredSize(new java.awt.Dimension(600, 375));
        tablaFrame.setResizable(false);
        tablaFrame.setSize(new java.awt.Dimension(600, 375));
        tablaFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipo 1", "Equipo 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setFocusable(false);
        tabla.setShowGrid(true);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
        }

        tablaFrame.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 6, -1, 130));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        tablaFrame.getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 120, 40));

        rehacer.setText("Rehacer equipos");
        rehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rehacerActionPerformed(evt);
            }
        });
        tablaFrame.getContentPane().add(rehacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 120, 40));

        inicio.setText("Volver al inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        tablaFrame.getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 120, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        nJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nJugadores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nJugadoresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Numero de jugadores:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nJugadores)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nJugadoresActionPerformed
        int MAX_JUGADORES = 16;
        int MIN_JUGADORES = 4;

        if (!nJugadores.getText().isBlank()) {
            try {
                int numJugadores = Integer.parseInt(nJugadores.getText());
                if (numJugadores < MIN_JUGADORES || numJugadores > MAX_JUGADORES) {
                    JOptionPane.showMessageDialog(this, (numJugadores > MAX_JUGADORES) ? "Ni Norberto tiene esa cantidad de contactos" : "Debe ser " + MIN_JUGADORES + " o más subnormal", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                listaJugadores = new ArrayList<>();
                int contador = 0;
                while (contador < numJugadores) {
                    String input = JOptionPane.showInputDialog(this, "Jugador " + (contador + 1), "Jugadores", -1);
                    if (input == null) {
                        return;
                    }
                    if (input.isBlank() || listaJugadores.contains(input)) {
                        JOptionPane.showMessageDialog(this, input.isBlank() ? "No puedes dejarlo en blanco" : "No puedes repetir nombres", "Error", JOptionPane.WARNING_MESSAGE);
                    } else {
                        listaJugadores.add(input);
                        contador++;
                    }

                }
                hacerEquipos(listaJugadores, numJugadores);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe ser un numero entero", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Introduzca un valor", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nJugadoresActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        setVisible(true);
        tablaFrame.setVisible(false);
        nJugadores.setText("");
        nJugadores.requestFocus();
    }//GEN-LAST:event_inicioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void rehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehacerActionPerformed
        hacerEquipos(listaJugadores, Integer.parseInt(nJugadores.getText()));
    }//GEN-LAST:event_rehacerActionPerformed

    private void hacerEquipos(ArrayList<String> listaJugadores, int numJugadores) {
        ArrayList<String> parejas = new ArrayList<>();
        int fila = 0;
        int columna = 0;
        int nRandom;
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
        do {
            model.addRow(new Object[]{});
        } while (model.getRowCount() != (Math.ceil(Double.parseDouble(String.valueOf(numJugadores)) / 4)));
        while (parejas.size() < listaJugadores.size()) {
            String j1;
            do {
                nRandom = (int) (Math.random() * listaJugadores.size());
                j1 = listaJugadores.get(nRandom);
            } while (parejas.contains(listaJugadores.get(nRandom)));
            parejas.add(j1);
            String j2 = "";
            if (parejas.size() != listaJugadores.size()) {
                do {
                    nRandom = (int) (Math.random() * listaJugadores.size());
                    j2 = listaJugadores.get(nRandom);
                } while (parejas.contains(listaJugadores.get(nRandom)));
            }
            parejas.add(j2);

            if (listaJugadores.size() % 4 == 0) {
                model.setValueAt(j1 + (!j2.isBlank() ? " y " + j2 : ""), fila, columna);
            } else if (listaJugadores.size() == parejas.size()) {
                model.setValueAt(j1, fila, columna);
                model.setValueAt(j2, fila, columna + 1);
            } else {
                model.setValueAt(j1 + (!j2.isBlank() ? " y " + j2 : ""), fila, columna);
            }

            columna++;

            if (columna == 2) {
                columna = 0;
                fila++;
            }

        }
        tablaFrame.setVisible(true);
        setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nJugadores;
    private javax.swing.JButton rehacer;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    private javax.swing.JFrame tablaFrame;
    // End of variables declaration//GEN-END:variables
}
