/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author usuario
 */
public class E144 extends javax.swing.JFrame {

    /**
     * Creates new form E144
     */
    double num1;
    double num2;
    boolean operador;

    public E144() {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        eventosNumeros();
        eventosOperaciones();
        lVentanaNumSuperior.setText("");
        operador = false;
    }

    public void eventosNumeros() {
        JButton jButtons[] = new JButton[]{b0, b1, b2, b3, b4, b5, b6, b7, b8, b9};
        for (JButton button : jButtons) {
            button.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonNumeros(evt);
                }
            });
        }
    }

    public void eventosOperaciones() {
        JButton jButtons[] = new JButton[]{bSuma, bResta, bX, bDiv};
        for (JButton button : jButtons) {
            button.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonOperaciones(evt);
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bAC = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bPorcentaje = new javax.swing.JButton();
        bDiv = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bX = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bResta = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bSuma = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bComa = new javax.swing.JButton();
        bIgual = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lVentanaNumSuperior = new javax.swing.JLabel();
        lVentanaNums = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 290));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 10, 10));

        bAC.setBackground(new java.awt.Color(51, 51, 51));
        bAC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAC.setForeground(new java.awt.Color(255, 51, 51));
        bAC.setText("AC");
        bAC.setBorder(null);
        bAC.setBorderPainted(false);
        bAC.setFocusPainted(false);
        bAC.setIconTextGap(0);
        bAC.setRequestFocusEnabled(false);
        bAC.setRolloverEnabled(false);
        bAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bACActionPerformed(evt);
            }
        });
        jPanel1.add(bAC);

        bAtras.setBackground(new java.awt.Color(51, 51, 51));
        bAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAtras.setForeground(new java.awt.Color(255, 51, 51));
        bAtras.setText("<-");
        bAtras.setBorder(null);
        bAtras.setBorderPainted(false);
        bAtras.setFocusPainted(false);
        bAtras.setIconTextGap(0);
        bAtras.setRequestFocusEnabled(false);
        bAtras.setRolloverEnabled(false);
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(bAtras);

        bPorcentaje.setBackground(new java.awt.Color(51, 51, 51));
        bPorcentaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPorcentaje.setForeground(new java.awt.Color(255, 51, 51));
        bPorcentaje.setText("%");
        bPorcentaje.setBorder(null);
        bPorcentaje.setBorderPainted(false);
        bPorcentaje.setFocusPainted(false);
        bPorcentaje.setIconTextGap(0);
        bPorcentaje.setRequestFocusEnabled(false);
        bPorcentaje.setRolloverEnabled(false);
        jPanel1.add(bPorcentaje);

        bDiv.setBackground(new java.awt.Color(51, 51, 51));
        bDiv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bDiv.setForeground(new java.awt.Color(255, 51, 51));
        bDiv.setText("/");
        bDiv.setBorder(null);
        bDiv.setBorderPainted(false);
        bDiv.setFocusPainted(false);
        bDiv.setIconTextGap(0);
        bDiv.setRequestFocusEnabled(false);
        bDiv.setRolloverEnabled(false);
        jPanel1.add(bDiv);

        b7.setBackground(new java.awt.Color(51, 51, 51));
        b7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.setBorder(null);
        b7.setBorderPainted(false);
        b7.setFocusPainted(false);
        b7.setIconTextGap(0);
        b7.setRequestFocusEnabled(false);
        b7.setRolloverEnabled(false);
        jPanel1.add(b7);

        b8.setBackground(new java.awt.Color(51, 51, 51));
        b8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.setBorder(null);
        b8.setBorderPainted(false);
        b8.setFocusPainted(false);
        b8.setIconTextGap(0);
        b8.setRequestFocusEnabled(false);
        b8.setRolloverEnabled(false);
        jPanel1.add(b8);

        b9.setBackground(new java.awt.Color(51, 51, 51));
        b9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.setBorder(null);
        b9.setBorderPainted(false);
        b9.setFocusPainted(false);
        b9.setIconTextGap(0);
        b9.setRequestFocusEnabled(false);
        b9.setRolloverEnabled(false);
        jPanel1.add(b9);

        bX.setBackground(new java.awt.Color(51, 51, 51));
        bX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bX.setForeground(new java.awt.Color(255, 51, 51));
        bX.setText("x");
        bX.setBorder(null);
        bX.setBorderPainted(false);
        bX.setFocusPainted(false);
        bX.setIconTextGap(0);
        bX.setRequestFocusEnabled(false);
        bX.setRolloverEnabled(false);
        jPanel1.add(bX);

        b4.setBackground(new java.awt.Color(51, 51, 51));
        b4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.setBorder(null);
        b4.setBorderPainted(false);
        b4.setFocusPainted(false);
        b4.setIconTextGap(0);
        b4.setRequestFocusEnabled(false);
        b4.setRolloverEnabled(false);
        jPanel1.add(b4);

        b5.setBackground(new java.awt.Color(51, 51, 51));
        b5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.setBorder(null);
        b5.setBorderPainted(false);
        b5.setFocusPainted(false);
        b5.setIconTextGap(0);
        b5.setRequestFocusEnabled(false);
        b5.setRolloverEnabled(false);
        jPanel1.add(b5);

        b6.setBackground(new java.awt.Color(51, 51, 51));
        b6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.setBorder(null);
        b6.setBorderPainted(false);
        b6.setFocusPainted(false);
        b6.setIconTextGap(0);
        b6.setRequestFocusEnabled(false);
        b6.setRolloverEnabled(false);
        jPanel1.add(b6);

        bResta.setBackground(new java.awt.Color(51, 51, 51));
        bResta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bResta.setForeground(new java.awt.Color(255, 51, 51));
        bResta.setText("-");
        bResta.setBorder(null);
        bResta.setBorderPainted(false);
        bResta.setFocusPainted(false);
        bResta.setIconTextGap(0);
        bResta.setRequestFocusEnabled(false);
        bResta.setRolloverEnabled(false);
        jPanel1.add(bResta);

        b1.setBackground(new java.awt.Color(51, 51, 51));
        b1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.setBorder(null);
        b1.setBorderPainted(false);
        b1.setFocusPainted(false);
        b1.setIconTextGap(0);
        b1.setRequestFocusEnabled(false);
        b1.setRolloverEnabled(false);
        jPanel1.add(b1);

        b2.setBackground(new java.awt.Color(51, 51, 51));
        b2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.setBorder(null);
        b2.setBorderPainted(false);
        b2.setFocusPainted(false);
        b2.setIconTextGap(0);
        b2.setRequestFocusEnabled(false);
        b2.setRolloverEnabled(false);
        jPanel1.add(b2);

        b3.setBackground(new java.awt.Color(51, 51, 51));
        b3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.setBorder(null);
        b3.setBorderPainted(false);
        b3.setFocusPainted(false);
        b3.setIconTextGap(0);
        b3.setRequestFocusEnabled(false);
        b3.setRolloverEnabled(false);
        jPanel1.add(b3);

        bSuma.setBackground(new java.awt.Color(51, 51, 51));
        bSuma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bSuma.setForeground(new java.awt.Color(255, 51, 51));
        bSuma.setText("+");
        bSuma.setBorder(null);
        bSuma.setBorderPainted(false);
        bSuma.setFocusPainted(false);
        bSuma.setIconTextGap(0);
        bSuma.setRequestFocusEnabled(false);
        bSuma.setRolloverEnabled(false);
        bSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSumaActionPerformed(evt);
            }
        });
        jPanel1.add(bSuma);

        bSalir.setBackground(new java.awt.Color(51, 51, 51));
        bSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("SALIR");
        bSalir.setBorder(null);
        bSalir.setBorderPainted(false);
        bSalir.setFocusPainted(false);
        bSalir.setIconTextGap(0);
        bSalir.setRequestFocusEnabled(false);
        bSalir.setRolloverEnabled(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel1.add(bSalir);

        b0.setBackground(new java.awt.Color(51, 51, 51));
        b0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.setBorder(null);
        b0.setBorderPainted(false);
        b0.setFocusPainted(false);
        b0.setIconTextGap(0);
        b0.setRequestFocusEnabled(false);
        b0.setRolloverEnabled(false);
        jPanel1.add(b0);

        bComa.setBackground(new java.awt.Color(51, 51, 51));
        bComa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bComa.setForeground(new java.awt.Color(255, 255, 255));
        bComa.setText(",");
        bComa.setBorder(null);
        bComa.setBorderPainted(false);
        bComa.setFocusPainted(false);
        bComa.setIconTextGap(0);
        bComa.setRequestFocusEnabled(false);
        bComa.setRolloverEnabled(false);
        bComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComaActionPerformed(evt);
            }
        });
        jPanel1.add(bComa);

        bIgual.setBackground(new java.awt.Color(51, 51, 51));
        bIgual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bIgual.setForeground(new java.awt.Color(255, 51, 51));
        bIgual.setText("=");
        bIgual.setBorder(null);
        bIgual.setBorderPainted(false);
        bIgual.setFocusPainted(false);
        bIgual.setIconTextGap(0);
        bIgual.setRequestFocusEnabled(false);
        bIgual.setRolloverEnabled(false);
        bIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIgualActionPerformed(evt);
            }
        });
        jPanel1.add(bIgual);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        lVentanaNumSuperior.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lVentanaNumSuperior.setForeground(new java.awt.Color(255, 255, 255));
        lVentanaNumSuperior.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lVentanaNumSuperior.setText("0");

        lVentanaNums.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lVentanaNums.setForeground(new java.awt.Color(255, 255, 255));
        lVentanaNums.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lVentanaNums.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lVentanaNumSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lVentanaNums, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(lVentanaNumSuperior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lVentanaNums)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNumeros(java.awt.event.ActionEvent evt) {
        JButton boton = (JButton) evt.getSource();
        if (lVentanaNums.getText().equals("0") || operador) {
            lVentanaNums.setText("");
            operador = false;
        }
        lVentanaNums.setText(lVentanaNums.getText() + boton.getText());
    }

    private void botonOperaciones(java.awt.event.ActionEvent evt) {
        num1 = Double.parseDouble(lVentanaNums.getText().replace(",", "."));
        
        JButton boton = (JButton) evt.getSource();
        lVentanaNumSuperior.setText(lVentanaNums.getText() + boton.getText());
        operador = true;
        System.out.println(num1);
    }

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComaActionPerformed
        if (!lVentanaNums.getText().contains(","))
            lVentanaNums.setText(lVentanaNums.getText() + ",");
    }//GEN-LAST:event_bComaActionPerformed

    private void bIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIgualActionPerformed
        num2 = Double.parseDouble(lVentanaNums.getText());
        lVentanaNumSuperior.setText(String.valueOf(num1 + num2));
    }//GEN-LAST:event_bIgualActionPerformed

    private void bACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bACActionPerformed
        lVentanaNums.setText("0");
        lVentanaNumSuperior.setText("");
    }//GEN-LAST:event_bACActionPerformed

    private void bSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSumaActionPerformed

    }//GEN-LAST:event_bSumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E144.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E144.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E144.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E144.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E144().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bAC;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bComa;
    private javax.swing.JButton bDiv;
    private javax.swing.JButton bIgual;
    private javax.swing.JButton bPorcentaje;
    private javax.swing.JButton bResta;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bSuma;
    private javax.swing.JButton bX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lVentanaNumSuperior;
    private javax.swing.JLabel lVentanaNums;
    // End of variables declaration//GEN-END:variables
}
